"""End-to-end tests for the full assessment lifecycle.

These tests exercise the entire agent pipeline against a staging/test
environment.  They require real Azure infrastructure (or a Docker Compose
stack that emulates it) and are marked @pytest.mark.e2e + @pytest.mark.slow
so they only run in a dedicated E2E environment.

Environment variables required:
  E2E_API_BASE_URL      — Base URL of the deployed API (e.g. http://localhost:8080)
  E2E_BEARER_TOKEN      — A valid JWT (can be generated by a test identity)
  E2E_TENANT_ID         — UUID of the pre-seeded test tenant
  E2E_SUBSCRIPTION_ID   — UUID of the Azure subscription under test
  E2E_POLL_TIMEOUT_S    — Seconds to wait for assessment to complete (default 300)
  E2E_POLL_INTERVAL_S   — Polling interval in seconds (default 5)
"""

from __future__ import annotations

import os
import time
import uuid
from typing import Any

import httpx
import pytest

pytestmark = [pytest.mark.e2e, pytest.mark.slow]


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


def _env(key: str, default: str | None = None) -> str:
    val = os.getenv(key, default)
    if val is None:
        pytest.skip(f"E2E environment variable {key} not set")
    return val


@pytest.fixture(scope="session")
def api_base() -> str:
    return _env("E2E_API_BASE_URL", "http://localhost:8080")


@pytest.fixture(scope="session")
def auth_headers() -> dict[str, str]:
    token = _env("E2E_BEARER_TOKEN", None)
    return {"Authorization": f"Bearer {token}"}


@pytest.fixture(scope="session")
def tenant_id() -> str:
    return _env("E2E_TENANT_ID", None)


@pytest.fixture(scope="session")
def subscription_id() -> str:
    return _env("E2E_SUBSCRIPTION_ID", None)


@pytest.fixture(scope="session")
def poll_timeout() -> int:
    return int(_env("E2E_POLL_TIMEOUT_S", "300"))


@pytest.fixture(scope="session")
def poll_interval() -> int:
    return int(_env("E2E_POLL_INTERVAL_S", "5"))


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _post(
    client: httpx.Client,
    url: str,
    json: dict[str, Any],
    headers: dict[str, str],
) -> httpx.Response:
    r = client.post(url, json=json, headers=headers, timeout=30)
    r.raise_for_status()
    return r


def _get(
    client: httpx.Client,
    url: str,
    headers: dict[str, str],
) -> httpx.Response:
    r = client.get(url, headers=headers, timeout=30)
    r.raise_for_status()
    return r


def _poll_until(
    client: httpx.Client,
    url: str,
    headers: dict[str, str],
    *,
    terminal_statuses: set[str],
    timeout_s: int,
    interval_s: int,
) -> dict[str, Any]:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        r = _get(client, url, headers)
        payload = r.json()
        if payload.get("status") in terminal_statuses:
            return payload
        time.sleep(interval_s)
    pytest.fail(f"Timed out after {timeout_s}s waiting for {url} to reach {terminal_statuses}")


# ---------------------------------------------------------------------------
# Smoke tests
# ---------------------------------------------------------------------------


class TestHealthEndpoints:
    def test_liveness_returns_200(self, api_base: str) -> None:
        with httpx.Client() as client:
            r = client.get(f"{api_base}/healthz", timeout=5)
        assert r.status_code == 200
        assert r.json().get("status") == "ok"

    def test_readiness_returns_200_or_503(self, api_base: str) -> None:
        with httpx.Client() as client:
            r = client.get(f"{api_base}/readyz", timeout=5)
        assert r.status_code in (200, 503)


# ---------------------------------------------------------------------------
# Full assessment lifecycle
# ---------------------------------------------------------------------------


class TestAssessmentLifecycle:
    def test_create_assessment_returns_201(
        self,
        api_base: str,
        auth_headers: dict[str, str],
        subscription_id: str,
    ) -> None:
        with httpx.Client() as client:
            r = _post(
                client,
                f"{api_base}/v1/assessments",
                json={
                    "subscription_ids": [subscription_id],
                    "pillar_filter": ["Security"],
                    "tag_filter": {},
                },
                headers=auth_headers,
            )
        assert r.status_code == 201
        body = r.json()
        assert "assessment_id" in body
        assert body["status"] in ("pending", "preparing")

    def test_assessment_reaches_completed_status(
        self,
        api_base: str,
        auth_headers: dict[str, str],
        subscription_id: str,
        poll_timeout: int,
        poll_interval: int,
    ) -> None:
        with httpx.Client() as client:
            create_r = _post(
                client,
                f"{api_base}/v1/assessments",
                json={
                    "subscription_ids": [subscription_id],
                    "pillar_filter": ["Security", "Reliability"],
                    "tag_filter": {},
                },
                headers=auth_headers,
            )
        assessment_id = create_r.json()["assessment_id"]

        with httpx.Client() as client:
            final = _poll_until(
                client,
                f"{api_base}/v1/assessments/{assessment_id}",
                auth_headers,
                terminal_statuses={"completed", "failed"},
                timeout_s=poll_timeout,
                interval_s=poll_interval,
            )

        assert (
            final["status"] == "completed"
        ), f"Assessment {assessment_id} ended in unexpected status: {final['status']}"

    def test_completed_assessment_has_findings(
        self,
        api_base: str,
        auth_headers: dict[str, str],
        subscription_id: str,
        poll_timeout: int,
        poll_interval: int,
    ) -> None:
        with httpx.Client() as client:
            create_r = _post(
                client,
                f"{api_base}/v1/assessments",
                json={
                    "subscription_ids": [subscription_id],
                    "pillar_filter": ["Security"],
                    "tag_filter": {},
                },
                headers=auth_headers,
            )
        assessment_id = create_r.json()["assessment_id"]

        with httpx.Client() as client:
            _poll_until(
                client,
                f"{api_base}/v1/assessments/{assessment_id}",
                auth_headers,
                terminal_statuses={"completed"},
                timeout_s=poll_timeout,
                interval_s=poll_interval,
            )
            findings_r = _get(
                client,
                f"{api_base}/v1/assessments/{assessment_id}/findings",
                auth_headers,
            )

        body = findings_r.json()
        assert "items" in body
        assert "total" in body
        # For any real subscription, there should be at least some findings
        assert body["total"] >= 0  # >= 0 is deliberately permissive

    def test_completed_assessment_has_report_url(
        self,
        api_base: str,
        auth_headers: dict[str, str],
        subscription_id: str,
        poll_timeout: int,
        poll_interval: int,
    ) -> None:
        with httpx.Client() as client:
            create_r = _post(
                client,
                f"{api_base}/v1/assessments",
                json={
                    "subscription_ids": [subscription_id],
                    "pillar_filter": ["Security"],
                    "tag_filter": {},
                },
                headers=auth_headers,
            )
        assessment_id = create_r.json()["assessment_id"]

        with httpx.Client() as client:
            _poll_until(
                client,
                f"{api_base}/v1/assessments/{assessment_id}",
                auth_headers,
                terminal_statuses={"completed"},
                timeout_s=poll_timeout,
                interval_s=poll_interval,
            )
            report_r = _get(
                client,
                f"{api_base}/v1/assessments/{assessment_id}/report",
                auth_headers,
            )

        body = report_r.json()
        assert "pdf_url" in body or "xlsx_url" in body

        # Verify the URL is a time-limited SAS URL, not a stored path
        for key in ("pdf_url", "xlsx_url"):
            if key in body and body[key]:
                url = body[key]
                assert url.startswith("https://")
                # SAS URLs contain 'sig=' parameter
                assert "sig=" in url, f"{key} is not a SAS URL"


# ---------------------------------------------------------------------------
# Security boundary tests
# ---------------------------------------------------------------------------


class TestSecurityBoundaries:
    def test_missing_auth_returns_401(self, api_base: str) -> None:
        with httpx.Client() as client:
            r = client.get(f"{api_base}/v1/assessments", timeout=5)
        assert r.status_code == 401

    def test_invalid_token_returns_401(self, api_base: str) -> None:
        with httpx.Client() as client:
            r = client.get(
                f"{api_base}/v1/assessments",
                headers={"Authorization": "Bearer not.a.real.token"},
                timeout=5,
            )
        assert r.status_code == 401

    def test_cross_tenant_assessment_returns_404(
        self, api_base: str, auth_headers: dict[str, str]
    ) -> None:
        fake_assessment_id = str(uuid.uuid4())
        with httpx.Client() as client:
            r = client.get(
                f"{api_base}/v1/assessments/{fake_assessment_id}",
                headers=auth_headers,
                timeout=5,
            )
        # Either 404 (not found) or 403 (forbidden) is acceptable
        assert r.status_code in (404, 403)

    def test_security_headers_present(self, api_base: str) -> None:
        with httpx.Client() as client:
            r = client.get(f"{api_base}/healthz", timeout=5)
        assert r.headers.get("x-content-type-options") == "nosniff"
        assert r.headers.get("x-frame-options") == "DENY"

    def test_docs_disabled_in_production(self, api_base: str) -> None:
        with httpx.Client() as client:
            r = client.get(f"{api_base}/docs", timeout=5)
        # Docs must be disabled in production — 404 is expected
        assert r.status_code == 404
