"""Alembic migration environment — asyncpg dialect via SQLAlchemy asyncio extension.

Autogenerate support: all SQLAlchemy models in waf_shared.db.models are imported
so that `alembic revision --autogenerate` can diff them against the live schema.
The initial migrations (0001-0003) were written as raw DDL. Subsequent migrations
may use either raw DDL or autogenerated declarative-style operations.
"""

from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig
from pathlib import Path
from urllib.parse import quote_plus

from dotenv import load_dotenv

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# Import all models so Alembic sees every table in Base.metadata.
from waf_shared.db.models import Base  # noqa: F401  (side-effect import)

config = context.config

# Load .env before any os.environ reads.
# Path is resolved relative to alembic.ini so this works regardless of the
# working directory from which `alembic` is invoked.
# override=False: real env vars (CI secrets, K8s env injection) take precedence
# over .env values, which is correct for production deployment.
_ini_dir = (
    Path(config.config_file_name).resolve().parent
    if config.config_file_name is not None
    else Path.cwd()
)
load_dotenv(_ini_dir / ".env", override=False)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _get_url() -> str:
    """Build the async DSN from environment variables.

    sqlalchemy.url in alembic.ini is intentionally left blank — this function
    is the single source of truth for the connection string so that local dev
    (.env), CI (exported vars), and production (K8s env injection) all use the
    same path without manual intervention.

    The postgresql+asyncpg:// scheme is required by SQLAlchemy's async engine.
    Do NOT use this URL with asyncpg.create_pool() directly — that function
    requires plain postgresql://.
    """
    user = os.environ.get("DB_USER", "wafagent")
    password = quote_plus(os.environ.get("DB_PASSWORD", "changeme_local_only"))
    host = os.environ.get("DB_HOST", "localhost")
    port = os.environ.get("DB_PORT", "5432")
    name = os.environ.get("DB_NAME", "wafagent")
    return f"postgresql+asyncpg://{user}:{password}@{host}:{port}/{name}"


def run_migrations_offline() -> None:
    """Run migrations without a live DB connection (generates SQL script)."""
    context.configure(
        url=_get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        include_schemas=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        include_schemas=True,
        # Tell autogenerate to treat existing enums as already-created by migrations.
        include_object=_include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def _include_object(
    obj: object,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: object,
) -> bool:
    """Exclude internal PostgreSQL schemas from autogenerate."""
    if type_ == "schema" and name not in (None, "public"):
        return False
    return True


async def run_async_migrations() -> None:
    section = config.get_section(config.config_ini_section) or {}
    section["sqlalchemy.url"] = _get_url()

    connectable = async_engine_from_config(
        section,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
